CaseMRI_Before:
    feature_mode: radi
    n_workers: 8
    image_ext:
        - 'nii.gz'
    cohort_dir:
        - '/mnt/hd0/project_large_files/bee/caseMRI_data/before/YCPH'
        - '/mnt/hd0/project_large_files/bee/caseMRI_data/before/SSPH'
        - '/mnt/hd0/project_large_files/bee/caseMRI_data/before/RHWU'
    cohort_name:
        - 'YCPH'
        - 'SSPH'
        - 'RHWU'
    clinical_data:
        - '/mnt/hd0/original_datasets/Prostate_DWI/YCPH.xlsx'
        - '/mnt/hd0/original_datasets/Prostate_DWI/SSPH.xlsx'
        - '/mnt/hd0/original_datasets/Prostate_DWI/RHWU.xlsx'
    clinical_column:
        - 'Age_Low_High'
        - 'PSA_Normal_Intermediate_High'
    # feature_path: '/mnt/hd0/project_large_files/bee/Case4_3cohorts_before_3/features.xlsx'
    save_dir: '/mnt/hd0/project_large_files/bee/deploy_test/Case4_3cohorts_before_4'
    seed: 2023

CaseMRI_After:
    feature_mode: radi
    n_workers: 8
    image_ext:
        - 'nii.gz'
    cohort_dir:
        - '/mnt/hd0/project_large_files/bee/caseMRI_data/after/YCPH'
        - '/mnt/hd0/project_large_files/bee/caseMRI_data/after/SSPH_crop'
        - '/mnt/hd0/project_large_files/bee/caseMRI_data/after/RHWU'
    cohort_name:
        - 'YCPH'
        - 'SSPH'
        - 'RHWU'
    clinical_data:
        - '/mnt/hd0/original_datasets/Prostate_DWI_2/YCPH.xlsx'
        - '/mnt/hd0/original_datasets/Prostate_DWI_2/SSPH.xlsx'
        - '/mnt/hd0/original_datasets/Prostate_DWI_2/RHWU.xlsx'
    clinical_column:
        - 'Age_Low_High'
        - 'PSA_Normal_Intermediate_High'
    # feature_path: '/mnt/hd0/project_large_files/bee/Case4_3cohorts_after_3/features.xlsx'
    save_dir: '/mnt/hd0/project_large_files/bee/deploy_test/Case4_3cohorts_after_4_2cohort'
    seed: 2023