CaseWSI:
    n_workers: 8
    cohort_dir:
        # - '/mnt/hd0/project_large_files/bee/WSIs/TCGA'
        # - '/mnt/hd0/project_large_files/bee/WSIs/GDPH'
        # - '/mnt/hd0/project_large_files/bee/WSIs/FAHKU'
        # - '/mnt/hd0/project_large_files/bee/WSIs/FAHZU'
        - /mnt/hd0/project_large_files/bee/caseWSI/TCGA
        - /mnt/hd0/project_large_files/bee/caseWSI/GDPH
        - /mnt/hd0/project_large_files/bee/caseWSI/FAHKU
        - /mnt/hd0/project_large_files/bee/caseWSI/FAHZU
    cohort_name:
        - 'TCGA'
        - 'GDPH'
        - 'FAHKU'
        - 'FAHZU'
    clinical_data:
        - '/mnt/hd0/project_large_files/bee/caseWSI/TCGA.xlsx'
        - '/mnt/hd0/project_large_files/bee/caseWSI/GDPH.xlsx'
        - '/mnt/hd0/project_large_files/bee/caseWSI/FAHKU.xlsx'
        - '/mnt/hd0/project_large_files/bee/caseWSI/FAHZU.xlsx'
    clinical_column:
        - 'Age_Low_High'
        - 'Gender'
    image_ext:
        - '.png'
    save_dir: '/data/project_large_files/bee/CaseTwo4ChortsWSI'
    feature_path: '/mnt/hd0/project_large_files/bee/CaseTwo4ChortsWSI/features.xlsx'