CaseTMA:
    feature_mode: path
    n_workers: 8
    cohort_dir:
        - '/mnt/hd0/project_large_files/bee/VTMA_v3/SUQH/imgs'
        - '/mnt/hd0/project_large_files/bee/VTMA_v3/QDUH/imgs'
        - '/mnt/hd0/project_large_files/bee/VTMA_v3/SHSU/imgs'
    image_ext:
        - 'png'
    cohort_name:
        - 'VTMA-1'
        - 'VTMA-2'
        - 'VTMA-3'
    clinical_data:
        - '/mnt/hd0/project_large_files/bee/VTMA_v3/SUQH/clinical.xlsx'
        - '/mnt/hd0/project_large_files/bee/VTMA_v3/QDUH/clinical.xlsx'
        - '/mnt/hd0/project_large_files/bee/VTMA_v3/SHSU/clinical.xlsx'
    clinical_column:
        - 'Invasion'
        - 'Overgrade'
    save_dir: '/data/project_large_files/bee/final_test/VTMA'
    feature_path: '/mnt/hd0/project_large_files/bee/CaseVTMA_v3/features.xlsx'